version: "3"

services:
  api:
    image: target/consensource-api:local
    build:
      context: api
  cli:
    image: target/consensource-cli:local
    build:
      context: cli
  processor:
    image: target/consensource-processor:local
    build:
      context: processor
  sds:
    image: target/consensource-ui:local
    build:
      context: sds
